Resources:
  Networking:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
  NetworkingPublicSubnet1Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/17
      VpcId:
        Ref: Networking
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      MapPublicIpOnLaunch: true
  NetworkingPublicSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: Networking
  NetworkingPublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: NetworkingPublicSubnet1RouteTable
      SubnetId:
        Ref: NetworkingPublicSubnet1Subnet
  NetworkingPublicSubnet1DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: NetworkingPublicSubnet1RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: NetworkingIGW
    DependsOn:
      - NetworkingVPCGW
  NetworkingPublicSubnet1EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  NetworkingPublicSubnet1NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - NetworkingPublicSubnet1EIP
          - AllocationId
      SubnetId:
        Ref: NetworkingPublicSubnet1Subnet
  NetworkingPrivateSubnet1Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.128.0/17
      VpcId:
        Ref: Networking
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      MapPublicIpOnLaunch: false
  NetworkingPrivateSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: Networking
  NetworkingPrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: NetworkingPrivateSubnet1RouteTable
      SubnetId:
        Ref: NetworkingPrivateSubnet1Subnet
  NetworkingPrivateSubnet1DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: NetworkingPrivateSubnet1RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: NetworkingPublicSubnet1NATGateway
  NetworkingIGW:
    Type: AWS::EC2::InternetGateway
  NetworkingVPCGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: Networking
      InternetGatewayId:
        Ref: NetworkingIGW
  IDE:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      InstanceType: t3.small
      Description: Sample Cloud9 IDE for FRB Hackathon
      Name: FRB Hackathon Demo
      SubnetId:
        Ref: NetworkingPublicSubnet1Subnet
Outputs:
  Cloud9Endpoint:
    Description: Use this URL to access your Cloud9 IDE in a browser
    Value:
      Fn::Sub:
        - https://${region}.console.aws.amazon.com/cloud9/home/environments/${physicalId}?permissions=owner
        - region:
            Ref: AWS::Region
          physicalId:
            Ref: IDE

